### ISSUE TITLE
Mock application user

### ISSUE THREAD

**Issue by zs-dima** [purplenoodlesoop/purple-starter#60]
Could be nice to add basic interface and scope to manage application user
Current/selected user could be optional - so starter could work without required login or user selection

**Comment by purplenoodlesoop** [comment]
Hello @zs-dima!

Thanks for the issues, but I'm afraid that user-related features are out of the starter's scope. 

Not all applications use the concept of current users and sessions, and when developing an MVP I'd say it's even counterproductive to introduce that concept from the start. Because of that very reason, the starter lack user-based, and app-based/shared settings – everything is shared in that form.

Hope that clears things out :)
